#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Stock.Resource", IsApplication=true)]

namespace Stock
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BotaoCadastrar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BotaoLogar = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int BotoesPadrao = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ceta = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int @checked = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int edit = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int fundo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icone = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int menu = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int pencil = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int search = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int selector = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int stock = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07002d
			public const int btnAddProduto = 2131165229;
			
			// aapt resource value: 0x7f07002a
			public const int btnCadastrar = 2131165226;
			
			// aapt resource value: 0x7f070008
			public const int btnEncontrarProdutoEstoque = 2131165192;
			
			// aapt resource value: 0x7f070029
			public const int btnLogar = 2131165225;
			
			// aapt resource value: 0x7f070028
			public const int btnLogarUsuario = 2131165224;
			
			// aapt resource value: 0x7f070017
			public const int btnMaisEdProduto = 2131165207;
			
			// aapt resource value: 0x7f070023
			public const int btnMaisQuantidade = 2131165219;
			
			// aapt resource value: 0x7f070018
			public const int btnMenosEdProduto = 2131165208;
			
			// aapt resource value: 0x7f070024
			public const int btnMenosQuantidade = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int btnSalvarCadastarProduto = 2131165221;
			
			// aapt resource value: 0x7f070019
			public const int btnSalvarEditarProduto = 2131165209;
			
			// aapt resource value: 0x7f07001f
			public const int btnSalvarNovoUsuario = 2131165215;
			
			// aapt resource value: 0x7f07002e
			public const int btnVerificarEstoque = 2131165230;
			
			// aapt resource value: 0x7f070002
			public const int imageView1 = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int imgImage = 2131165193;
			
			// aapt resource value: 0x7f070005
			public const int imgVoltar = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f07000c
			public const int linearLayout2 = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int linearLayout3 = 2131165198;
			
			// aapt resource value: 0x7f070011
			public const int linearLayout4 = 2131165201;
			
			// aapt resource value: 0x7f070003
			public const int lnBarra = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int lnMenu = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int lnProcurarActionBarEstoque = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int lnVoltarActionBarEstoque = 2131165188;
			
			// aapt resource value: 0x7f07001a
			public const int lnlInicial = 2131165210;
			
			// aapt resource value: 0x7f07002f
			public const int lvListaDeProdutos = 2131165231;
			
			// aapt resource value: 0x7f07000a
			public const int textView1 = 2131165194;
			
			// aapt resource value: 0x7f07000f
			public const int textView2 = 2131165199;
			
			// aapt resource value: 0x7f070012
			public const int textView3 = 2131165202;
			
			// aapt resource value: 0x7f07001b
			public const int txtClickMe = 2131165211;
			
			// aapt resource value: 0x7f07001e
			public const int txtConSenhaNovoUsuario = 2131165214;
			
			// aapt resource value: 0x7f070014
			public const int txtEditarProdutoNome = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int txtEditarProdutoPreco = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int txtEditarProdutoQtd = 2131165206;
			
			// aapt resource value: 0x7f07001c
			public const int txtEmailNovoUsuario = 2131165212;
			
			// aapt resource value: 0x7f070026
			public const int txtEmailUsuario = 2131165222;
			
			// aapt resource value: 0x7f070007
			public const int txtEncontrarProdutoEstoque = 2131165191;
			
			// aapt resource value: 0x7f07000d
			public const int txtNomeAdapter = 2131165197;
			
			// aapt resource value: 0x7f070020
			public const int txtNomeCadastrarProduto = 2131165216;
			
			// aapt resource value: 0x7f070010
			public const int txtPrecoAdapter = 2131165200;
			
			// aapt resource value: 0x7f070021
			public const int txtPrecoCadastrarProduto = 2131165217;
			
			// aapt resource value: 0x7f07002b
			public const int txtQtdProdutos = 2131165227;
			
			// aapt resource value: 0x7f070013
			public const int txtQuantidadeAdapter = 2131165203;
			
			// aapt resource value: 0x7f070022
			public const int txtQuantidadeEmEstoque = 2131165218;
			
			// aapt resource value: 0x7f07001d
			public const int txtSenhaNovoUsuario = 2131165213;
			
			// aapt resource value: 0x7f070027
			public const int txtSenhaUsuario = 2131165223;
			
			// aapt resource value: 0x7f07000b
			public const int txtUsuarioAdm = 2131165195;
			
			// aapt resource value: 0x7f07002c
			public const int txtValorMercadorias = 2131165228;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActionBarMenuUsuario = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ActionBarVerificarEstoque = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ActionMenuVerde = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int AdapterViewAdm = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int AdapterViewProdutos = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int EditarProdutos = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ImgInicial = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int JanelaCadastrar = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int JanelaCadastrarProduto = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int JanelaLogin = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Main = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int PageUsuario = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int VerificarEstoque = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int CustomActionBarTheme = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int MyActionBar = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int dialog_animation = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
